[project]
name = "proof-of-skill"
requirements = []
[contracts.proof-of-skill]
path = "contracts/proof-of-skill.clar"
clarity_version = 2
epoch = 2.5

[contracts.skill-verifier-trait]
path = "contracts/traits/skill-verifier-trait.clar"
clarity_version = 2
epoch = 2.5
