[project]
name = "proof-of-skill"
authors = []
telemetry = true

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.proof-of-skill]
path = "contracts/proof-of-skill.clar"
depends_on = []

[contracts.skill-verifier-trait]
path = "contracts/traits/skill-verifier-trait.clar"
depends_on = []
